.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. # Sourcecode link to GitHub
.. |SHIELD:svg:pyVHDLModel-github| image:: https://img.shields.io/badge/VHDL-pyVHDLModel-29b6f6.svg?longCache=true&style=flat-square&logo=GitHub&labelColor=0277bd
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel
.. |SHIELD:png:pyVHDLModel-github| image:: https://raster.shields.io/badge/VHDL-pyVHDLModel-29b6f6.svg?longCache=true&style=flat-square&logo=GitHub&labelColor=0277bd
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel

.. # Sourcecode license
.. |SHIELD:svg:pyVHDLModel-src-license| image:: https://img.shields.io/pypi/l/pyVHDLModel?longCache=true&style=flat-square&logo=GitHub&label=code%20license
   :alt: Code license
   :height: 22
   :target: Code-License.html
.. |SHIELD:png:pyVHDLModel-src-license| image:: https://img.shields.io/pypi/l/pyVHDLModel?longCache=true&style=flat-square&logo=GitHub&label=code%20license
   :alt: Code license
   :height: 22
   :target: https://github.com/VHDL/pyVHDLModel/blob/master/LICENSE.md

.. # GitHub tag
.. |SHIELD:svg:pyVHDLModel-tag| image:: https://img.shields.io/github/v/tag/vhdl/pyVHDLModel?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel/tags
.. |SHIELD:png:pyVHDLModel-tag| image:: https://raster.shields.io/github/v/tag/vhdl/pyVHDLModel?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel/tags

.. # GitHub release date
.. |SHIELD:svg:pyVHDLModel-date| image:: https://img.shields.io/github/release-date/vhdl/pyVHDLModel?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel/releases
.. |SHIELD:png:pyVHDLModel-date| image:: https://raster.shields.io/github/release-date/vhdl/pyVHDLModel?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel/releases

.. # GitHub/Libraries dependent projects
.. |SHIELD:svg:pyVHDLModel-lib-dep| image:: https://img.shields.io/librariesio/dependent-repos/pypi/pyVHDLModel?longCache=true&style=flat-square
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel/network/dependents
.. |SHIELD:png:pyVHDLModel-lib-dep| image:: https://raster.shields.io/librariesio/dependent-repos/pypi/pyVHDLModel?longCache=true&style=flat-square
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel/network/dependents

.. # GHA test and coverage
.. |SHIELD:svg:pyVHDLModel-gha-test| image:: https://img.shields.io/github/workflow/status/vhdl/pyVHDLModel/Unit%20Testing,%20Coverage%20Collection,%20Package,%20Release,%20Documentation%20and%20Publish/master?longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel/actions?query=workflow%3A%22Test+and+Coverage%22
.. |SHIELD:png:pyVHDLModel-gha-test| image:: https://img.shields.io/github/workflow/status/vhdl/pyVHDLModel/Unit%20Testing,%20Coverage%20Collection,%20Package,%20Release,%20Documentation%20and%20Publish/master?longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel/actions?query=workflow%3A%22Test+and+Coverage%22

.. # Codacy - quality
.. |SHIELD:svg:pyVHDLModel-codacy-quality| image:: https://img.shields.io/codacy/grade/2286426d2b11417e90010427b7fed8e7?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/manual/vhdl/pyVHDLModel
.. |SHIELD:png:pyVHDLModel-codacy-quality| image:: https://raster.shields.io/codacy/grade/2286426d2b11417e90010427b7fed8e7?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/manual/vhdl/pyVHDLModel

.. # Codacy - coverage
.. |SHIELD:svg:pyVHDLModel-codacy-coverage| image:: https://img.shields.io/codacy/coverage/2286426d2b11417e90010427b7fed8e7?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/manual/vhdl/pyVHDLModel
.. |SHIELD:png:pyVHDLModel-codacy-coverage| image:: https://raster.shields.io/codacy/coverage/2286426d2b11417e90010427b7fed8e7?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/manual/vhdl/pyVHDLModel

.. # Codecov - coverage
.. |SHIELD:svg:pyVHDLModel-codecov-coverage| image:: https://img.shields.io/codecov/c/github/vhdl/pyVHDLModel?longCache=true&style=flat-square
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/vhdl/pyVHDLModel
.. |SHIELD:png:pyVHDLModel-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/vhdl/pyVHDLModel?longCache=true&style=flat-square
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/vhdl/pyVHDLModel

.. # Libraries - source rank
.. |SHIELD:svg:pyVHDLModel-lib-rank| image:: https://img.shields.io/librariesio/sourcerank/pypi/pyVHDLModel?longCache=true&style=flat-square
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/vhdl/pyVHDLModel/sourcerank
.. |SHIELD:png:pyVHDLModel-lib-rank| image:: https://raster.shields.io/librariesio/sourcerank/pypi/pyVHDLModel?longCache=true&style=flat-square
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/vhdl/pyVHDLModel/sourcerank

.. # GHA release
.. |SHIELD:svg:pyVHDLModel-gha-release| image:: https://img.shields.io/github/workflow/status/vhdl/pyVHDLModel/Release?longCache=true&style=flat-square&label=release&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Release Status
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel/actions?query=workflow%3A%22Release%22
.. |SHIELD:png:pyVHDLModel-gha-release| image:: https://img.shields.io/github/workflow/status/vhdl/pyVHDLModel/Release?longCache=true&style=flat-square&label=release&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Release Status
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel/actions?query=workflow%3A%22Release%22

.. # PyPI tag
.. |SHIELD:svg:pyVHDLModel-pypi-tag| image:: https://img.shields.io/pypi/v/pyVHDLModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyVHDLModel/
.. |SHIELD:png:pyVHDLModel-pypi-tag| image:: https://raster.shields.io/pypi/v/pyVHDLModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyVHDLModel/

.. # PyPI project status
.. |SHIELD:svg:pyVHDLModel-pypi-status| image:: https://img.shields.io/pypi/status/pyVHDLModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22
.. |SHIELD:png:pyVHDLModel-pypi-status| image:: https://raster.shields.io/pypi/status/pyVHDLModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22

.. # PyPI Python versions
.. |SHIELD:svg:pyVHDLModel-pypi-python| image:: https://img.shields.io/pypi/pyversions/pyVHDLModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22
.. |SHIELD:png:pyVHDLModel-pypi-python| image:: https://raster.shields.io/pypi/pyversions/pyVHDLModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22

.. # Libraries - status
.. |SHIELD:svg:pyVHDLModel-lib-status| image:: https://img.shields.io/librariesio/release/pypi/pyVHDLModel?longCache=true&style=flat-square
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/vhdl/pyVHDLModel
.. |SHIELD:png:pyVHDLModel-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/pyVHDLModel?longCache=true&style=flat-square
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/vhdl/pyVHDLModel

.. # Requires - status
.. |SHIELD:svg:pyVHDLModel-req-status| image:: https://img.shields.io/requires/github/VHDL/pyVHDLModel?longCache=true&style=flat-square
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/VHDL/pyVHDLModel/requirements/?branch=master
.. |SHIELD:png:pyVHDLModel-req-status| image:: https://raster.shields.io/requires/github/VHDL/pyVHDLModel?longCache=true&style=flat-square
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/VHDL/pyVHDLModel/requirements/?branch=master

.. # Documentation license
.. |SHIELD:svg:pyVHDLModel-doc-license| image:: https://img.shields.io/badge/doc%20license-CC--BY%204.0-green?longCache=true&style=flat-square
   :alt: Documentation License
   :height: 22
   :target: Doc-License.html
.. |SHIELD:png:pyVHDLModel-doc-license| image:: https://raster.shields.io/badge/doc%20license-CC--BY%204.0-green?longCache=true&style=flat-square
   :alt: Documentation License
   :height: 22
   :target: https://github.com/VHDL/pyVHDLModel/blob/master/doc/Doc-License.rst

.. # GHPages - read now
.. |SHIELD:svg:pyVHDLModel-ghp-doc| image:: https://img.shields.io/website?longCache=true&style=flat-square&label=vhdl.github.io%2FpyVHDLModel&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fvhdl.github.io%2FpyVHDLModel%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://vhdl.github.io/pyVHDLModel/
.. |SHIELD:png:pyVHDLModel-ghp-doc| image:: https://raster.shields.io/website?longCache=true&style=flat-square&label=vhdl.github.io%2FpyVHDLModel&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fvhdl.github.io%2FpyVHDLModel%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://vhdl.github.io/pyVHDLModel/
