.. # This file provides the following shields: travis-ci appveyor tag release
   # license mailing gitter issues-new issues-open issues-closed issues-pr
   # issues-pr-closed github gh-logo

.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. |SHIELD:svg:pyVHDLModel-github| image:: https://img.shields.io/badge/vhdl-pyVHDLModel-323131?logo=github&longCache=true
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel
.. |SHIELD:png:pyVHDLModel-github| image:: https://raster.shields.io/badge/vhdl-pyVHDLModel-323131?logo=github&longCache=true
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel

.. |SHIELD:svg:pyVHDLModel-license| image:: https://img.shields.io/badge/Apache%20License,%202.0-bd0000?longCache=true&label=license&logo=Apache&logoColor=D22128
   :alt: License
   :height: 22
.. |SHIELD:png:pyVHDLModel-license| image:: https://raster.shields.io/badge/Apache%20License,%202.0-bd0000?longCache=true&label=license&logo=Apache&logoColor=D22128
   :alt: License
   :height: 22

.. |SHIELD:svg:pyVHDLModel-tag| image:: https://img.shields.io/github/v/tag/vhdl/pyVHDLModel?logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel/tags
.. |SHIELD:png:pyVHDLModel-tag| image:: https://raster.shields.io/github/v/tag/vhdl/pyVHDLModel?logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel/tags

.. |SHIELD:svg:pyVHDLModel-release| image:: https://img.shields.io/github/v/release/vhdl/pyVHDLModel?logo=GitHub&include_prereleases
   :alt: GitHub release (latest SemVer incl. including pre-releases
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel/releases/latest
.. |SHIELD:png:pyVHDLModel-release| image:: https://raster.shields.io/github/v/release/vhdl/pyVHDLModel?logo=GitHub&include_prereleases
   :alt: GitHub release (latest SemVer incl. including pre-releases
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel/releases/latest

.. |SHIELD:svg:pyVHDLModel-date| image:: https://img.shields.io/github/release-date/vhdl/pyVHDLModel?logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel/releases
.. |SHIELD:png:pyVHDLModel-date| image:: https://raster.shields.io/github/release-date/vhdl/pyVHDLModel?logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel/releases

.. |SHIELD:svg:pyVHDLModel-lib-status| image:: https://img.shields.io/librariesio/release/pypi/pyVHDLModel
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/vhdl/pyVHDLModel
.. |SHIELD:png:pyVHDLModel-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/pyVHDLModel
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/vhdl/pyVHDLModel

.. |SHIELD:svg:pyVHDLModel-req-status| image:: https://img.shields.io/requires/github/vhdl/pyVHDLModel
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/vhdl/pyVHDLModel/requirements/?branch=main
.. |SHIELD:png:pyVHDLModel-req-status| image:: https://raster.shields.io/requires/github/vhdl/pyVHDLModel
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/vhdl/pyVHDLModel/requirements/?branch=main

.. |SHIELD:svg:pyVHDLModel-pypi-tag| image:: https://img.shields.io/pypi/v/pyVHDLModel?logo=PyPI
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyVHDLModel/
.. |SHIELD:png:pyVHDLModel-pypi-tag| image:: https://raster.shields.io/pypi/v/pyVHDLModel?logo=PyPI
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyVHDLModel/

.. |SHIELD:svg:pyVHDLModel-pypi-status| image:: https://img.shields.io/pypi/status/pyVHDLModel?logo=PyPI
   :alt: PyPI - Status
   :height: 22
.. |SHIELD:png:pyVHDLModel-pypi-status| image:: https://raster.shields.io/pypi/status/pyVHDLModel?logo=PyPI
   :alt: PyPI - Status
   :height: 22

.. |SHIELD:svg:pyVHDLModel-pypi-python| image:: https://img.shields.io/pypi/pyversions/pyVHDLModel?logo=PyPI
   :alt: PyPI - Python Version
   :height: 22
.. |SHIELD:png:pyVHDLModel-pypi-python| image:: https://raster.shields.io/pypi/pyversions/pyVHDLModel?logo=PyPI
   :alt: PyPI - Python Version
   :height: 22

.. |SHIELD:svg:pyVHDLModel-lib-dep| image:: https://img.shields.io/librariesio/dependent-repos/pypi/pyVHDLModel
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel/network/dependents
.. |SHIELD:png:pyVHDLModel-lib-dep| image:: https://raster.shields.io/librariesio/dependent-repos/pypi/pyVHDLModel
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://github.com/vhdl/pyVHDLModel/network/dependents

.. |SHIELD:svg:pyVHDLModel-codacy-quality| image:: https://img.shields.io/codacy/grade/2286426d2b11417e90010427b7fed8e7?logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/manual/vhdl/pyVHDLModel
.. |SHIELD:png:pyVHDLModel-codacy-quality| image:: https://raster.shields.io/codacy/grade/2286426d2b11417e90010427b7fed8e7?logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/manual/vhdl/pyVHDLModel

.. |SHIELD:svg:pyVHDLModel-codacy-coverage| image:: https://img.shields.io/codacy/coverage/2286426d2b11417e90010427b7fed8e7?logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/manual/vhdl/pyVHDLModel
.. |SHIELD:png:pyVHDLModel-codacy-coverage| image:: https://raster.shields.io/codacy/coverage/2286426d2b11417e90010427b7fed8e7?logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/manual/vhdl/pyVHDLModel

.. |SHIELD:svg:pyVHDLModel-codecov-coverage| image:: https://img.shields.io/codecov/c/github/vhdl/pyVHDLModel
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/vhdl/pyVHDLModel
.. |SHIELD:png:pyVHDLModel-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/vhdl/pyVHDLModel
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/vhdl/pyVHDLModel

.. |SHIELD:svg:pyVHDLModel-lib-rank| image:: https://img.shields.io/librariesio/sourcerank/pypi/pyVHDLModel
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/vhdl/pyVHDLModel/sourcerank
.. |SHIELD:png:pyVHDLModel-lib-rank| image:: https://raster.shields.io/librariesio/sourcerank/pypi/pyVHDLModel
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/vhdl/pyVHDLModel/sourcerank

.. |SHIELD:svg:pyVHDLModel-rtd| image:: https://img.shields.io/readthedocs/pyVHDLModel
   :alt: Read the Docs
   :height: 22
   :target: https://pyVHDLModel.readthedocs.io/en/latest/
.. |SHIELD:png:pyVHDLModel-rtd| image:: https://raster.shields.io/readthedocs/pyVHDLModel
   :alt: Read the Docs
   :height: 22
   :target: https://pyVHDLModel.readthedocs.io/en/latest/
